compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: false
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
main_training_function: main
mixed_precision: bf16
num_machines: 12
num_processes: 48
rdzv_backend: static
same_network: true
use_cpu: false
